services:
  myurls:
    build: .
    image: cjpjxjx/myurls:latest
    container_name: myurls
    restart: unless-stopped
    ports:
      - "8006:8006"
    environment:
      - TZ=Asia/Shanghai
      - MYURLS_PORT=8006
      - MYURLS_DOMAIN=url.cencs.com
      - MYURLS_PROTO=https
    volumes:
      - ./data/myurls/logs:/app/logs      
    depends_on:
      - myurls-redis
    entrypoint: ["/app/myurls", "-domain", "url.cencs.com", "-conn", myurls-redis:6379]

  myurls-redis:
    image: "redis:7"
    container_name: myurls-redis
    restart: unless-stopped
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data/redis:/data
